/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Clients: () => import('#controllers/clients_controller'),
  Gateways: () => import('#controllers/gateways_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Purchases: () => import('#controllers/purchases_controller'),
  Users: () => import('#controllers/users_controller'),
}
